import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';

function formatDate(date: Date | null | undefined): string {
  if (!date) return 'N/A';
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

function getProgress(status: string): number {
  const map: Record<string, number> = {
    Pending: 20,
    'Under Review': 50,
    'Correction Needed': 40,
    Approved: 90,
    Denied: 100,
  };
  return map[status] || 0;
}

function getPipeline(status: string): { stage: string; label: string; active: boolean; complete: boolean }[] {
  const allStages = [
    { stage: 'submitted', label: 'Submitted', order: 0 },
    { stage: 'validated', label: 'Validated', order: 1 },
    { stage: 'review', label: 'Under Review', order: 2 },
    { stage: 'decision', label: 'Decision', order: 3 },
    { stage: 'completed', label: 'Completed', order: 4 },
  ];

  let activeIndex = 0;
  if (status === 'Pending') activeIndex = 0;
  else if (status === 'Correction Needed') activeIndex = 1;
  else if (status === 'Under Review') activeIndex = 2;
  else if (status === 'Denied' || status === 'Approved') activeIndex = 3;
  else if (status === 'Completed') activeIndex = 4;

  const completeIndex = status === 'Denied' || status === 'Approved' ? 4 : activeIndex;

  return allStages.map((s, i) => ({
    stage: s.stage,
    label: s.label,
    active: i === activeIndex,
    complete: i < completeIndex,
  }));
}

function getChecklist(status: string): { item: string; done: boolean }[] {
  const base = [
    { item: 'Proof of Residence', done: true },
    { item: 'Medical Records', done: true },
    { item: 'Completed Claim Form', done: status !== 'Pending' },
    { item: 'Authorization Letter', done: status === 'Under Review' || status === 'Approved' || status === 'Denied' },
    { item: 'ID Verification', done: status === 'Approved' },
  ];
  return base;
}

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const trackingId = searchParams.get('trackingId');

    if (!trackingId || trackingId.trim() === '') {
      return NextResponse.json(
        { error: 'Tracking ID is required' },
        { status: 400 }
      );
    }

    const claim = await db.claim.findUnique({
      where: { trackingId: trackingId.trim() },
      include: {
        claimant: {
          select: {
            firstName: true,
            lastName: true,
            email: true,
            phone: true,
          },
        },
        history: {
          orderBy: { date: 'desc' },
        },
      },
    });

    if (!claim) {
      return NextResponse.json(
        { error: `No claim found with tracking ID "${trackingId}". Please verify your tracking ID and try again.` },
        { status: 404 }
      );
    }

    const progress = getProgress(claim.status);

    const report = {
      trackingId: claim.trackingId,
      claimant: claim.claimant
        ? `${(claim.claimant.firstName?.charAt(0) || '?')}. ${claim.claimant.lastName || 'Unknown'}`
        : 'Unknown Claimant',
      status: claim.status,
      progress,
      claimType: claim.claimType || 'General Claim',
      filedDate: formatDate(claim.filedDate),
      lastUpdated: formatDate(claim.lastUpdated),
      description: claim.description || 'No description available.',
      notes: claim.notes || 'No additional notes.',
      nextSteps: claim.nextSteps || 'No next steps available.',
      history: claim.history.map((h) => ({
        status: h.status,
        notes: h.notes || '',
        date: formatDate(h.date),
      })),
      pipeline: getPipeline(claim.status),
      checklist: getChecklist(claim.status),
      generatedAt: formatDate(new Date()),
      disclaimer:
        'This is an unofficial summary generated by ClaimGuard Pro for informational purposes only. It does not constitute legal advice. For official claim documents, please contact the claims administrator or call (484) 968-1529.',
    };

    return NextResponse.json({
      success: true,
      report,
    });
  } catch (error) {
    console.error('Error generating claim report:', error);
    return NextResponse.json(
      { error: 'An internal error occurred. Please try again later.' },
      { status: 500 }
    );
  }
}
